# Generated by Django 4.1 on 2022-09-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
